echo "MMMMMMMMNmdddddddmNMMMMMMMMMMMMNmmddddddmNMMMMMMMM"
sleep 0.5
echo "MMMMMmhyyyyyyyyyyyyhdNMMMMMMNdhyyyyyyyyyyyyhmNMMMM"
sleep 0.5
echo "MMMdyyyyyyyyyyyyyyyyyydNMMNdyyyyyyyyyyyyyyyyyydNMM"
sleep 0.5
echo "MNhyyyyyyyyyyyyyyyyyyyyyNNhyyyyyyyyyyyyyyyyyyyyhNM"
sleep 0.5
echo "NhyyyyyyyyyyyyyyyyyyyyyyhhyyyyyyyyyyyyyyyyyyyyyyyN"
sleep 0.5
echo "dyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyd"
sleep 0.5
echo "hyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyh"
sleep 0.5
echo "hyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyh"
sleep 0.5
echo "dyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyd"
sleep 0.5
echo "NyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyN"
sleep 0.5
echo "MdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydM"
sleep 0.5
echo "MMdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydMM"
sleep 0.5
echo "MMMmhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhmMMM"
sleep 0.5
echo "MMMMNdhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdNMMMM"
sleep 0.5
echo "MMMMMMNmhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhmNMMMMMM"
sleep 0.5
echo "MMMMMMMMMmdyyyyyyyyyyyyyyyyyyyyyyyyyyyydmMMMMMMMMM"
sleep 0.5
echo "MMMMMMMMMMMNmhyyyyyyyyyyyyyyyyyyyyyyhmNMMMMMMMMMMM"
sleep 0.5
echo "MMMMMMMMMMMMMMNdhyyyyyyyyyyyyyyyyhdNMMMMMMMMMMMMMM"
sleep 0.5
echo "MMMMMMMMMMMMMMMMMmdyyyyyyyyyyyyhmMMMMMMMMMMMMMMMMM"
sleep 0.5
echo "MMMMMMMMMMMMMMMMMMMNdhyyyyyyydNMMMMMMMMMMMMMMMMMMM"
sleep 0.5
echo "MMMMMMMMMMMMMMMMMMMMMMmhyyhmMMMMMMMMMMMMMMMMMMMMMM"
sleep 0.5
echo "MMMMMMMMMMMMMMMMMMMMMMMMdmMMMMMMMMMMMMMMMMMMMMMMMM"
sleep 1
figlet 'Happy wedding'
